### PR TITLE
Kakshay clean

### PR DESCRIPTION
**Pull request by kakshay21**
https://github.com/plone/Products.CMFPlone/issues/1975

### CODE REVIEW

**Comment by gforcada** [comment]
@kakshay21 thanks for contributing! And extra thanks for doing all the work right from the very beginning! (changelog entry and running the pull request jenkins job)

@mauritsvanrees do we need an upgrade step for that?

**Comment by mauritsvanrees** [comment]
I would say no upgrade step specifically for `plone.app.discussion` is needed. I think it is best if we create an upgrade step in `plone.app.upgrade` that goes through all workflows in `portal_workflow` and removes this permission from the list of managed permissions and from each state.

BTW, I do not notice anything going wrong when the workflow contains a managed permission which no longer exists: as a quick test, I edited the one state comment workflow and renamed 'Change portal events' to 'Maurits portal events' . On a new site with this, I did not notice anything going wrong.

**Comment by gforcada** [comment]
@mauritsvanrees I thought so myself, but do we still want to clean it up? What if third party add-ons rely on it? I'm not sure if it would be a good idea to remove it on an upgrade step...

**Comment by mauritsvanrees** [comment]
We could create a function in `plone.app.upgrade` that removes the permission from one workflow. Then in an upgrade step we call this function for all default Plone workflows. Add-ons can then reuse this function if they have their own workflow.

**Pull request merged**
