### PR TITLE
Remove old translations

### LINKED ISSUE #205: (re)move translations?
@erral you might know better than me 🍀 

While running `codespell` in this repository, oh surprise, the translations in [`i18n`](https://github.com/plone/plone.app.discussion/tree/master/plone/app/discussion/i18n) folder produce false positives.

While `codespell` does [not ignore `.po` files by default](https://github.com/codespell-project/codespell/issues/2790), we have to find a solution.

But back to the point, are those translations there actually being used? 🤔 

The only `MessageFactory` that is created is for `plone`:

```bash
plone/app/discussion/__init__.py:1:from zope.i18nmessageid import MessageFactory
plone/app/discussion/__init__.py:4:_ = MessageFactory("plone")
```

So the translations in the `i18n` could be removed or merged/migrated to `plone.app.locales`? 🤔 

TIA! 🙇🏾

### PR DESCRIPTION
**Pull request by gforcada**
Closes #205

### CODE REVIEW

**Review by erral — APPROVED** [review]

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
Quite a few test failures, are those related?

**Comment by gforcada** [comment]
No idea, the robot tests failing are related to tests, so it might be indeed related 🤔 

Let's try again 🍀 

@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@davisagli seems that it was a commit done directly to `master` branch

We were not seeing that in jenkins as `mr.roboto` somehow did not add `plone.app.discussion` to `checkouts.cfg` 🤔 

Not it should be all good, right Jenkins? 🤞🏾 

@jenkins-plone-org please run jobs

**Pull request merged**
