### PR TITLE
Index comments on Solr

### PR DESCRIPTION
**Pull request by gforcada**
As https://github.com/collective/collective.solr/pull/102 finally got merged, it is time to use that on plone.app.discussion.

This minimal pull request is what is needed so that collective.solr (or other indexing tools) need to index comments on Solr.

Fixes (by ignoring) #77

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@ale-rt as far as I could see the methods there on ``tool.py`` are only used by the deprecated #114, but you are right, I should have kept them, removing a deprecated tool has nothing to do with this.

I will update the pull request, thanks for the review!! :bowing_man:

**Comment by ale-rt** [comment]
Thanks for clarifying! It's even fine to remove them if they are deprecated :)

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
I was about to close this one, but given that it still helps on removing the last usage of the deprecated comment indexing tool, I will keep it.

Let's see if the unrelated failures are fixed on a second run.

**Pull request merged**
