### PR TITLE
Apply hotfix 20161129 [master]

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
This needs fixes in the tests of CMFPlone and CMFPlacefulWorkflow.

**Comment by mauritsvanrees** [comment]
Jenkins tests combination for 5.1:

```
https://github.com/plone/plone.app.discussion/pull/115
https://github.com/plone/Products.CMFPlone/pull/1909
https://github.com/plone/Products.CMFPlacefulWorkflow/pull/11
```

**Comment by mauritsvanrees** [comment]
Jenkins tests combination for 5.0:

```
https://github.com/plone/plone.app.discussion/pull/115
https://github.com/plone/Products.CMFPlone/pull/1910
https://github.com/plone/Products.CMFPlacefulWorkflow/pull/12
```

**Comment by mauritsvanrees** [comment]
The failure on Jenkins 4.3 is a mistake by me. This plone.app.discussion branch is only for Plone 5.0 and 5.1. I copied the wrong pull request url when combining a bunch of pull requests.

**Comment by mauritsvanrees** [comment]
This is ready for review.
When approved, please merge in combination with the pull requests for two branches of CMFPlone and CMFPlacefulWorkflow. Or ask me to merge.

**Comment by jensens** [comment]
Except that we have a 4.3 test failure this looks good to me.

**Comment by mauritsvanrees** [comment]
The 4.3 test failure is no problem: there is no need to run this on 4.3, I just created a wrong job, and this will now forever be recorded as failure in the issue.

So I will merge.

**Pull request merged**
