### PR TITLE
Reindex comments when they are modified

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by ale-rt** [comment]
After merging this one I got some emails from jenkins.
Maybe because the PR is too old?

**Comment by gforcada** [comment]
@ale-rt yes, somehow the jenkins jobs where removed and as they were triggered again, jenkins went through all branches again to check for code-analysis errors. But you can safely ignore them

**Comment by gforcada** [comment]
@ale-rt thanks for merging btw!

**Comment by ale-rt** [comment]
Thank you for providing the patch!

**Pull request merged**
