### PR TITLE
Plone base overhaul

### PR DESCRIPTION
**Pull request by jensens**
- isort, black, pyupgrade 
- remove six and some bbb
- use plone.base and move annotation key over to here

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by ksuess — CHANGES_REQUESTED** [review]
LGTM. Just two docs that still have explicit unicode strings.

**Comment by jensens** [comment]
> LGTM. Just two docs that still have explicit unicode strings.

Can you give me a hint where? pyupgrade only covers code, so that is probably why.

**Review by petschki — APPROVED** [review]
LGTM

**Review by mauritsvanrees — APPROVED** [review]

**Comment by ksuess** [comment]
> > LGTM. Just two docs that still have explicit unicode strings.
> 
> Can you give me a hint where? pyupgrade only covers code, so that is probably why.

docs:
https://github.com/plone/plone.app.discussion/blob/bcb93157724d8044998853ab3a1f2a50ea99dda2/docs/source/howtos/howto_make_pad_work_with_a_dexterity_content_type.txt#L20-L28
https://github.com/plone/plone.app.discussion/blob/bcb93157724d8044998853ab3a1f2a50ea99dda2/docs/source/howtos/howto_extend_the_comment_form.txt#L59-L67

**Review by ksuess — APPROVED** [review]

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
