### PR TITLE
window load on moderation.js doesn't work on some version of FF and IE

### PR DESCRIPTION
**Pull request by eikichi18**
Hi,

I've changed the method that wait the page is loaded in moderation.js file becouse $(window).load doesn't work in some version of FF and IE. $(document).ready seems to work properly.

### CODE REVIEW

**Comment by jensens** [comment]
Please run the tests. if all is fine its ok to merge.

**Comment by eikichi18** [comment]
it seem that jenkins does not work.

**Comment by jensens** [comment]
Jenkins is back, I started the tests.

**Comment by eikichi18** [comment]
it seems that jenkins fails with tests that seems unrelated with my modification.

**Pull request merged**
