### PR TITLE
Events for Comment and Reply modification

### PR DESCRIPTION
**Pull request by ericof**
Implemented events:

- Comment modification: plone.app.discussion.interfaces.ICommentModifiedEvent
- Reply modification: plone.app.discussion.interfaces.IReplyModifiedEvent

### CODE REVIEW

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]

**Review by mauritsvanrees — COMMENTED** [review]
Seems okay.  I would think the existing `IObjectModifiedEvent` for `IComment` is enough. But I see the package already has custom events for adding and deleting, so then custom events for modifying make sense as well.

Will you forward port this to master?
(Or is this a back port from master?)

**Comment by ericof** [comment]
@mauritsvanrees The whole idea is to, later, also add these events to plone.app.contentrules (we had one use case for this in a client project)
I will forward port this to master (Is master Plone 6 only?)

**Comment by mauritsvanrees** [comment]
Ah, that can help.
Yes, master is for Plone 6 only.

**Comment by tisto** [comment]
@mauritsvanrees just wondering. Since when is p.a.discussion master Plone 6 only? This should be reflected in the README I guess...

**Comment by mauritsvanrees** [comment]
If the readme says for which Plone versions it is, then this information is probably best deleted. It is bound to get outdated without anyone noticing.
Buildout coredev 5.2 is using branch 3.4.x [since 7 months](https://github.com/plone/buildout.coredev/commit/70b51cd7c85f1f55f84ab261be1221c4e46dc3ad). Master has bootstrap 4 changes, that is the reason.

**Pull request merged**
