### PR TITLE
This will only show a bug when anon email is available and member tries ...

### PR DESCRIPTION
**Pull request by maartenkling**
...to comment

Do not merge until fixed

### CODE REVIEW

**Comment by tisto** [comment]
@maartenkling what's the status of this pull request? Do you want me to review it? Otherwise we should close the pull request.

**Comment by maartenkling** [comment]
@tisto this is only a proof that the current functionality isn't working, the test is correct

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/415/

**Comment by mauritsvanrees** [comment]
Closing this in favour of https://github.com/plone/plone.app.discussion/pull/102 which includes the test. Thanks for writing that, @maartenkling!

**Pull request closed without merging**
